source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Yodo1Games/MAS-Spec.git'

platform :ios, '13.0'

target 'Yodo1AdWrapper' do
  use_frameworks! :linkage => :static

  pod 'Yodo1MasCore', '4.17.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['SKIP_INSTALL'] = 'NO'
    end
  end
end
